version: '3.3'

networks:
  dojo_network:
    driver: bridge

services:
  express:
    image: express-image
    container_name: express
    build:
      context: ./express-image
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    networks:
      - dojo_network

  test:
    image: test-image
    container_name: test
    build:
      context: ./test-image
      dockerfile: Dockerfile
    networks:
      - dojo_network
    depends_on:
      - express
    
